baseURL: https://moment.kemeow.top/
languageCode: zh-Hans
theme: moments
pagination:
  pagerSize: 10    # 原 paginate
  path: "page"     # 原 paginatePath

params:
    title: "喵言堂"
    signature: "每一段旅行都有终点~"
    cover: "background.jpg"

    name: "克喵爱吃卤面"
    avatar: "avatar.png"

    experimental:
      comment: true

UTC时间转换: https://www.iamwawa.cn/timezone.html

